// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  turfId: __t.u32().name("turf_id"),
  voterId: __t.option(__t.u32()).name("voter_id"),
  volunteerId: __t.option(__t.u32()).name("volunteer_id"),
  eventType: __t.string().name("event_type"),
  status: __t.string(),
  message: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  createdAt: __t.timestamp().name("created_at"),
});
