// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  enabled: __t.bool(),
  virtualVolunteers: __t.u32().name("virtual_volunteers"),
  cursor: __t.u32(),
  ticks: __t.u32(),
  eventsEmitted: __t.u32().name("events_emitted"),
  updatedAt: __t.timestamp().name("updated_at"),
});
