// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  turfId: __t.u32().primaryKey().name("turf_id"),
  totalVoters: __t.u32().name("total_voters"),
  notContactedCount: __t.u32().name("not_contacted_count"),
  contactedCount: __t.u32().name("contacted_count"),
  literatureDroppedCount: __t.u32().name("literature_dropped_count"),
  refusedCount: __t.u32().name("refused_count"),
  donatedCount: __t.u32().name("donated_count"),
  activeVolunteerCount: __t.u32().name("active_volunteer_count"),
  updateCount: __t.u32().name("update_count"),
  lastEventAt: __t.option(__t.timestamp()).name("last_event_at"),
});
