// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Coordinate,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  neighborhood: __t.string(),
  centerLat: __t.f64().name("center_lat"),
  centerLng: __t.f64().name("center_lng"),
  get boundary() {
    return __t.array(Coordinate);
  },
  get walkRoute() {
    return __t.array(Coordinate).name("walk_route");
  },
});
