// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivityEvent = __t.object("ActivityEvent", {
  id: __t.u32(),
  turfId: __t.u32(),
  voterId: __t.option(__t.u32()),
  volunteerId: __t.option(__t.u32()),
  eventType: __t.string(),
  status: __t.string(),
  message: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  createdAt: __t.timestamp(),
});
export type ActivityEvent = __Infer<typeof ActivityEvent>;

export const Coordinate = __t.object("Coordinate", {
  lat: __t.f64(),
  lng: __t.f64(),
});
export type Coordinate = __Infer<typeof Coordinate>;

export const DerivedTurfImportRow = __t.object("DerivedTurfImportRow", {
  id: __t.u32(),
  name: __t.string(),
  neighborhood: __t.string(),
  centerLat: __t.f64(),
  centerLng: __t.f64(),
  get boundary() {
    return __t.array(Coordinate);
  },
  get walkRoute() {
    return __t.array(Coordinate);
  },
});
export type DerivedTurfImportRow = __Infer<typeof DerivedTurfImportRow>;

export const DerivedVoterImportRow = __t.object("DerivedVoterImportRow", {
  id: __t.u32(),
  turfId: __t.u32(),
  householdKey: __t.string(),
  registeredVoterCount: __t.u32(),
  householdName: __t.string(),
  address: __t.string(),
  precinct: __t.string(),
  sourceCity: __t.string(),
  sourceZip5: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
});
export type DerivedVoterImportRow = __Infer<typeof DerivedVoterImportRow>;

export const RegisteredVoter = __t.object("RegisteredVoter", {
  vuid: __t.string(),
  name: __t.string(),
  status: __t.string(),
  city: __t.string(),
  zip5: __t.string(),
  precinct: __t.string(),
  payload: __t.string(),
});
export type RegisteredVoter = __Infer<typeof RegisteredVoter>;

export const RegisteredVoterImportRow = __t.object("RegisteredVoterImportRow", {
  vuid: __t.string(),
  payload: __t.string(),
});
export type RegisteredVoterImportRow = __Infer<typeof RegisteredVoterImportRow>;

export const SimState = __t.object("SimState", {
  id: __t.u32(),
  enabled: __t.bool(),
  virtualVolunteers: __t.u32(),
  cursor: __t.u32(),
  ticks: __t.u32(),
  eventsEmitted: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type SimState = __Infer<typeof SimState>;

export const Turf = __t.object("Turf", {
  id: __t.u32(),
  name: __t.string(),
  neighborhood: __t.string(),
  centerLat: __t.f64(),
  centerLng: __t.f64(),
  get boundary() {
    return __t.array(Coordinate);
  },
  get walkRoute() {
    return __t.array(Coordinate);
  },
});
export type Turf = __Infer<typeof Turf>;

export const TurfStats = __t.object("TurfStats", {
  turfId: __t.u32(),
  totalVoters: __t.u32(),
  notContactedCount: __t.u32(),
  contactedCount: __t.u32(),
  literatureDroppedCount: __t.u32(),
  refusedCount: __t.u32(),
  donatedCount: __t.u32(),
  activeVolunteerCount: __t.u32(),
  updateCount: __t.u32(),
  lastEventAt: __t.option(__t.timestamp()),
});
export type TurfStats = __Infer<typeof TurfStats>;

export const Volunteer = __t.object("Volunteer", {
  id: __t.u32(),
  identity: __t.identity(),
  displayName: __t.string(),
  currentTurfId: __t.u32(),
  lat: __t.f64(),
  lng: __t.f64(),
  heading: __t.f64(),
  active: __t.bool(),
  isSimulated: __t.bool(),
  targetVoterId: __t.u32(),
  completedCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Volunteer = __Infer<typeof Volunteer>;

export const Voter = __t.object("Voter", {
  id: __t.u32(),
  turfId: __t.u32(),
  householdKey: __t.option(__t.string()),
  registeredVoterCount: __t.option(__t.u32()),
  householdName: __t.string(),
  address: __t.string(),
  precinct: __t.option(__t.string()),
  sourceCity: __t.option(__t.string()),
  sourceZip5: __t.option(__t.string()),
  lat: __t.f64(),
  lng: __t.f64(),
  status: __t.string(),
  lastContactedAt: __t.option(__t.timestamp()),
  lastContactedBy: __t.option(__t.u32()),
  attemptCount: __t.u16(),
  donationCents: __t.u32(),
  updatedSeq: __t.u32(),
});
export type Voter = __Infer<typeof Voter>;

