// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  currentTurfId: __t.u32().name("current_turf_id"),
  lat: __t.f64(),
  lng: __t.f64(),
  heading: __t.f64(),
  active: __t.bool(),
  isSimulated: __t.bool().name("is_simulated"),
  targetVoterId: __t.u32().name("target_voter_id"),
  completedCount: __t.u32().name("completed_count"),
  updatedAt: __t.timestamp().name("updated_at"),
});
