// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  turfId: __t.u32().name("turf_id"),
  householdKey: __t.option(__t.string()).name("household_key"),
  registeredVoterCount: __t.option(__t.u32()).name("registered_voter_count"),
  householdName: __t.string().name("household_name"),
  address: __t.string(),
  precinct: __t.option(__t.string()),
  sourceCity: __t.option(__t.string()).name("source_city"),
  sourceZip5: __t.option(__t.string()).name("source_zip_5"),
  lat: __t.f64(),
  lng: __t.f64(),
  status: __t.string(),
  lastContactedAt: __t.option(__t.timestamp()).name("last_contacted_at"),
  lastContactedBy: __t.option(__t.u32()).name("last_contacted_by"),
  attemptCount: __t.u16().name("attempt_count"),
  donationCents: __t.u32().name("donation_cents"),
  updatedSeq: __t.u32().name("updated_seq"),
});
