// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimTurfReducer from "../claim_turf_reducer";
import ClearDerivedDataReducer from "../clear_derived_data_reducer";
import CompleteTurfReducer from "../complete_turf_reducer";
import ImportDerivedDataBatchReducer from "../import_derived_data_batch_reducer";
import ImportRegisteredVotersReducer from "../import_registered_voters_reducer";
import ResetDemoDataReducer from "../reset_demo_data_reducer";
import SeedSimulationReducer from "../seed_simulation_reducer";
import SimulateTickReducer from "../simulate_tick_reducer";
import StopSimulationReducer from "../stop_simulation_reducer";
import UpdateVolunteerLocationReducer from "../update_volunteer_location_reducer";
import UpdateVoterStatusReducer from "../update_voter_status_reducer";

export type ClaimTurfParams = __Infer<typeof ClaimTurfReducer>;
export type ClearDerivedDataParams = __Infer<typeof ClearDerivedDataReducer>;
export type CompleteTurfParams = __Infer<typeof CompleteTurfReducer>;
export type ImportDerivedDataBatchParams = __Infer<typeof ImportDerivedDataBatchReducer>;
export type ImportRegisteredVotersParams = __Infer<typeof ImportRegisteredVotersReducer>;
export type ResetDemoDataParams = __Infer<typeof ResetDemoDataReducer>;
export type SeedSimulationParams = __Infer<typeof SeedSimulationReducer>;
export type SimulateTickParams = __Infer<typeof SimulateTickReducer>;
export type StopSimulationParams = __Infer<typeof StopSimulationReducer>;
export type UpdateVolunteerLocationParams = __Infer<typeof UpdateVolunteerLocationReducer>;
export type UpdateVoterStatusParams = __Infer<typeof UpdateVoterStatusReducer>;

